const fs=require("fs")
const path=require("path")
const filepath=path.join("./Day2","sample.txt")
console.log(filepath)
const data=fs.readFileSync("./sample.txt",'utf-8')
console.log(data)
fs.writeFileSync("./sample.txt","new content")
const data2=fs.readFileSync("./sample.txt",'utf-8')
console.log(data2)